### ISSUE TITLE
Sorting Problems Tracker

### ISSUE THREAD

**Issue by piedpipr** [piedpipr/DSA-Bootcamp-Java#4]
# Videos
- [ ] [Bubble Sort](https://youtu.be/F5MZyqRp_IM)
- [ ] [Selection Sort](https://youtu.be/Nd4SCCIHFWk)
- [ ] [Insertion Sort](https://youtu.be/By_5-RRqVeE)
- [ ] [Cycle Sort](https://www.youtube.com/watch?v=JfinxytTYFQ&list=RDCMUCBGOUQHNNtNGcGzVq5rIXjw&start_radio=1&rv=JfinxytTYFQ&t=2)
- [ ] [Merge Sort](https://youtu.be/iKGAgWdgoRk)
- [ ] [Quick Sort](https://youtu.be/Z8svOqamag8)

# Questions

## Easy
- [ ] [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/)
- [ ] [Majority Element](https://leetcode.com/problems/majority-element/)
- [ ] [Contains Duplicate](https://leetcode.com/problems/contains-duplicate/)
- [ ] [Missing Number](https://leetcode.com/problems/missing-number/)
- [ ] [Intersection of Two Arrays](https://leetcode.com/problems/intersection-of-two-arrays/)
- [ ] [Intersection of Two Arrays II](https://leetcode.com/problems/intersection-of-two-arrays-ii/)
- [ ] [Third Maximum Number](https://leetcode.com/problems/third-maximum-number/)
- [ ] [Assign Cookies](https://leetcode.com/problems/assign-cookies/)
- [ ] [Array Partition I](https://leetcode.com/problems/array-partition-i/)
- [ ] [Maximum Product of Three Numbers](https://leetcode.com/problems/maximum-product-of-three-numbers/)
- [ ] [Sort Array By Parity](https://leetcode.com/problems/sort-array-by-parity/)
- [ ] [Sort Array By Parity II](https://leetcode.com/problems/sort-array-by-parity-ii/)
- [ ] [Largest Perimeter Triangle](https://leetcode.com/problems/largest-perimeter-triangle/)
- [ ] [Squares of a Sorted Array](https://leetcode.com/problems/squares-of-a-sorted-array/)
- [ ] [Matrix Cells in Distance Order](https://leetcode.com/problems/matrix-cells-in-distance-order/)
- [ ] [Height Checker](https://leetcode.com/problems/height-checker/)
- [ ] [Relative Sort Array](https://leetcode.com/problems/relative-sort-array/)
- [ ] [Minimum Absolute Difference](https://leetcode.com/problems/minimum-absolute-difference/)
- [ ] [Rank Transform of an Array](https://leetcode.com/problems/rank-transform-of-an-array/)
- [ ] [Sort Integers by The Number of 1 Bits](https://leetcode.com/problems/sort-integers-by-the-number-of-1-bits/)
- [ ] [How Many Numbers Are Smaller Than the Current Number](https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/)
- [ ] [Maximum Product of Two Elements in an Array](https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/)
- [ ] [Average Salary Excluding the Minimum and Maximum Salary](https://leetcode.com/problems/average-salary-excluding-the-minimum-and-maximum-salary/)
- [ ] [Make Two Arrays Equal by Reversing Sub-arrays](https://leetcode.com/problems/make-two-arrays-equal-by-reversing-sub-arrays/)
- [ ] [Can Make Arithmetic Progression From Sequence](https://leetcode.com/problems/can-make-arithmetic-progression-from-sequence/)
- [ ] [Sort Array by Increasing Frequency](https://leetcode.com/problems/sort-array-by-increasing-frequency/)
- [ ] [Special Array With X Elements Greater Than or Equal X](https://leetcode.com/problems/special-array-with-x-elements-greater-than-or-equal-x/)
- [ ] [Find all numbers disappeared in an array](https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/)
- [ ] [Set Mismatch](https://leetcode.com/problems/set-mismatch/)
- [ ] [2Sum](https://leetcode.com/problems/two-sum/)

## Medium
- [ ] [3Sum](https://leetcode.com/problems/3sum/)
- [ ] [3Sum Closest](https://leetcode.com/problems/3sum-closest/)
- [ ] [4Sum](https://leetcode.com/problems/4sum/)
- [ ] [Group Anagrams](https://leetcode.com/problems/group-anagrams/)
- [ ] [Merge Intervals](https://leetcode.com/problems/merge-intervals/)
- [ ] [Sort Colors](https://leetcode.com/problems/sort-colors/)
- [ ] [Insertion Sort List](https://leetcode.com/problems/insertion-sort-list/)
- [ ] [Sort List](https://leetcode.com/problems/sort-list/)
- [ ] [Largest Number](https://leetcode.com/problems/largest-number/)
- [ ] [Kth Largest Element in an Array](https://leetcode.com/problems/kth-largest-element-in-an-array/)
- [ ] [Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/)
- [ ] [Find all Duplicates in an array](https://leetcode.com/problems/find-all-duplicates-in-an-array/)

## Hard
- [ ] [First missing Positive](https://leetcode.com/problems/first-missing-positive/)
